-- קודם מוחקים את הטבלאות שמכילות מפתחות זרים לאחרות
DROP TABLE IF EXISTS INSPECTION_LOG;
DROP TABLE IF EXISTS MAINTENANCE_TICKETS;
DROP TABLE IF EXISTS ASSETS;

-- רק עכשיו אפשר למחוק את טבלאות התשתית
DROP TABLE IF EXISTS STAFF;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS VENDORS;