-- שליפת כל הנתונים מכל הטבלאות במערכת
SELECT * FROM STAFF;
SELECT * FROM LOCATIONS;
SELECT * VALUES FROM VENDORS;
SELECT * FROM ASSETS;
SELECT * FROM MAINTENANCE_TICKETS;
SELECT * FROM INSPECTION_LOG;
