-- Data for table LOCATIONS
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (1, 10, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (2, 3, 'Roof', 'Staff Only');
INSERT INTO ININSERTTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (3, 3, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (4, 6, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (5, 12, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (6, 12, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (7, 7, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (8, 18, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (9, 6, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (10, 8, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (11, 6, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (12, 1, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (13, 20, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (14, 6, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (15, 14, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (16, 11, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (17, 6, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (18, 1, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (19, 12, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (20, 14, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (21, 7, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (22, 17, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (23, 7, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (24, 18, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (25, 13, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (26, 6, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (27, 14, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (28, 7, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (29, 13, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (30, 12, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (31, 12, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (32, 9, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (33, 7, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (34, 9, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (35, 18, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (36, 18, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (37, 11, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (38, 17, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (39, 19, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (40, 7, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (41, 17, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (42, 5, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (43, 7, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (44, 17, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (45, 10, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (46, 14, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (47, 14, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (48, 3, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (49, 14, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (50, 16, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (51, 14, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (52, 17, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (53, 6, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (54, 1, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (55, 3, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (56, 13, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (57, 5, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (58, 12, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (59, 2, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (60, 14, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (61, 8, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (62, 8, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (63, 12, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (64, 14, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (65, 3, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (66, 5, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (67, 17, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (68, 6, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (69, 4, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (70, 8, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (71, 2, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (72, 4, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (73, 2, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (74, 15, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (75, 20, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (76, 7, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (77, 12, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (78, 16, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (79, 8, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (80, 6, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (81, 18, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (82, 1, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (83, 12, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (84, 9, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (85, 18, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (86, 14, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (87, 14, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (88, 3, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (89, 3, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (90, 18, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (91, 13, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (92, 12, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (93, 3, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (94, 2, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (95, 13, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (96, 5, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (97, 18, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (98, 5, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (99, 11, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (100, 3, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (101, 9, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (102, 1, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (103, 5, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (104, 3, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (105, 14, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (106, 18, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (107, 8, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (108, 3, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (109, 5, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (110, 16, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (111, 3, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (112, 9, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (113, 10, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (114, 8, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (115, 1, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (116, 7, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (117, 15, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (118, 2, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (119, 14, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (120, 18, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (121, 5, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (122, 9, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (123, 6, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (124, 17, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (125, 6, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (126, 14, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (127, 12, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (128, 3, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (129, 17, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (130, 6, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (131, 12, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (132, 9, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (133, 15, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (134, 4, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (135, 5, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (136, 2, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (137, 15, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (138, 9, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (139, 1, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (140, 16, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (141, 1, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (142, 17, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (143, 13, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (144, 19, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (145, 7, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (146, 6, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (147, 8, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (148, 12, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (149, 20, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (150, 18, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (151, 8, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (152, 12, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (153, 7, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (154, 19, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (155, 14, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (156, 13, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (157, 10, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (158, 10, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (159, 16, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (160, 15, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (161, 19, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (162, 6, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (163, 20, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (164, 20, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (165, 9, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (166, 14, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (167, 14, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (168, 17, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (169, 13, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (170, 10, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (171, 2, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (172, 7, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (173, 18, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (174, 4, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (175, 5, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (176, 4, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (177, 11, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (178, 8, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (179, 17, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (180, 10, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (181, 8, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (182, 3, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (183, 1, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (184, 2, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (185, 9, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (186, 17, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (187, 19, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (188, 3, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (189, 12, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (190, 2, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (191, 18, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (192, 2, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (193, 19, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (194, 18, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (195, 2, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (196, 5, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (197, 4, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (198, 6, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (199, 14, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (200, 7, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (201, 12, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (202, 3, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (203, 17, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (204, 10, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (205, 14, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (206, 3, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (207, 14, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (208, 12, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (209, 20, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (210, 13, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (211, 12, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (212, 16, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (213, 20, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (214, 10, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (215, 18, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (216, 8, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (217, 8, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (218, 9, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (219, 13, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (220, 11, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (221, 9, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (222, 2, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (223, 17, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (224, 8, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (225, 10, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (226, 7, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (227, 17, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (228, 10, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (229, 9, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (230, 16, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (231, 9, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (232, 4, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (233, 4, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (234, 7, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (235, 19, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (236, 17, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (237, 9, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (238, 17, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (239, 10, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (240, 8, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (241, 15, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (242, 4, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (243, 4, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (244, 6, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (245, 16, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (246, 12, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (247, 13, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (248, 11, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (249, 12, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (250, 14, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (251, 4, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (252, 15, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (253, 16, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (254, 12, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (255, 7, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (256, 2, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (257, 19, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (258, 5, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (259, 11, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (260, 14, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (261, 10, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (262, 18, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (263, 9, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (264, 16, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (265, 9, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (266, 11, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (267, 20, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (268, 6, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (269, 1, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (270, 20, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (271, 10, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (272, 16, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (273, 15, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (274, 15, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (275, 1, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (276, 11, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (277, 2, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (278, 2, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (279, 18, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (280, 6, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (281, 10, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (282, 19, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (283, 6, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (284, 12, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (285, 2, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (286, 4, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (287, 8, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (288, 8, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (289, 11, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (290, 7, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (291, 3, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (292, 1, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (293, 4, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (294, 7, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (295, 9, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (296, 9, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (297, 9, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (298, 6, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (299, 16, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (300, 2, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (301, 10, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (302, 1, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (303, 10, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (304, 18, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (305, 6, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (306, 9, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (307, 7, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (308, 4, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (309, 17, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (310, 20, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (311, 8, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (312, 11, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (313, 9, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (314, 19, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (315, 12, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (316, 16, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (317, 17, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (318, 11, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (319, 9, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (320, 20, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (321, 9, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (322, 14, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (323, 12, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (324, 15, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (325, 4, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (326, 17, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (327, 2, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (328, 14, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (329, 8, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (330, 5, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (331, 20, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (332, 7, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (333, 11, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (334, 20, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (335, 16, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (336, 14, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (337, 18, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (338, 20, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (339, 14, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (340, 19, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (341, 4, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (342, 11, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (343, 5, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (344, 5, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (345, 8, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (346, 7, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (347, 9, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (348, 18, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (349, 18, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (350, 18, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (351, 6, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (352, 3, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (353, 17, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (354, 3, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (355, 10, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (356, 3, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (357, 14, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (358, 10, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (359, 7, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (360, 6, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (361, 20, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (362, 19, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (363, 7, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (364, 15, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (365, 16, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (366, 8, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (367, 9, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (368, 16, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (369, 8, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (370, 1, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (371, 11, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (372, 4, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (373, 7, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (374, 14, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (375, 4, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (376, 14, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (377, 8, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (378, 2, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (379, 7, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (380, 9, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (381, 8, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (382, 6, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (383, 8, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (384, 8, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (385, 15, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (386, 7, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (387, 1, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (388, 2, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (389, 1, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (390, 10, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (391, 20, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (392, 18, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (393, 1, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (394, 16, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (395, 19, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (396, 4, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (397, 13, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (398, 12, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (399, 12, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (400, 4, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (401, 19, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (402, 6, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (403, 6, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (404, 18, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (405, 11, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (406, 11, 'Gym', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (407, 18, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (408, 18, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (409, 6, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (410, 20, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (411, 17, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (412, 18, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (413, 9, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (414, 11, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (415, 10, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (416, 20, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (417, 16, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (418, 7, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (419, 17, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (420, 10, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (421, 6, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (422, 7, 'Suite 101', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (423, 2, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (424, 19, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (425, 14, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (426, 19, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (427, 19, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (428, 7, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (429, 14, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (430, 17, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (431, 16, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (432, 2, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (433, 10, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (434, 7, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (435, 4, 'Parking', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (436, 5, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (437, 11, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (438, 2, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (439, 14, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (440, 6, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (441, 8, 'Suite 101', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (442, 4, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (443, 5, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (444, 2, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (445, 13, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (446, 15, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (447, 13, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (448, 12, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (449, 5, 'Kitchen', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (450, 11, 'Restaurant', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (451, 7, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (452, 15, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (453, 19, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (454, 3, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (455, 9, 'Laundry Room', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (456, 4, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (457, 18, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (458, 20, 'Parking', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (459, 8, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (460, 15, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (461, 17, 'Suite 102', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (462, 12, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (463, 2, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (464, 19, 'Spa', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (465, 7, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (466, 17, 'Gym', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (467, 15, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (468, 20, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (469, 17, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (470, 3, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (471, 14, 'Lobby', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (472, 4, 'Suite 101', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (473, 12, 'Laundry Room', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (474, 3, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (475, 11, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (476, 14, 'Lobby', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (477, 19, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (478, 18, 'Laundry Room', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (479, 16, 'Roof', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (480, 16, 'Kitchen', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (481, 5, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (482, 4, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (483, 16, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (484, 12, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (485, 10, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (486, 17, 'Restaurant', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (487, 11, 'Suite 102', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (488, 19, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (489, 1, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (490, 11, 'Lobby', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (491, 9, 'Restaurant', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (492, 15, 'Suite 102', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (493, 5, 'Kitchen', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (494, 13, 'Roof', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (495, 16, 'Roof', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (496, 3, 'Parking', 'Public');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (497, 4, 'Gym', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (498, 6, 'Spa', 'Maintenance Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (499, 10, 'Spa', 'Staff Only');
INSERT INTO LOCATIONS (location_id, floor_number, area_name, access_level) VALUES (500, 11, 'Suite 102', 'Public');
