-- Data for table STAFF
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (1, 'Ephrayim', 'Asey', '186-690-8447', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (2, 'Gilda', 'Garvin', '675-350-7802', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (3, 'Elana', 'Bennallck', '649-420-4084', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (4, 'Laurie', 'Raeside', '655-234-8563', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (5, 'Essa', 'Nickless', '616-781-5266', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (6, 'Aguistin', 'Miell', '592-778-2564', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (7, 'Elisabeth', 'Broker', '319-654-6668', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (8, 'Noach', 'Eunson', '616-756-6065', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (9, 'Sapphire', 'Verbrugge', '462-824-6753', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (10, 'Silvana', 'Markey', '798-525-1679', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (11, 'Neysa', 'Gladstone', '632-384-3888', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (12, 'Audrie', 'Romaint', '568-569-3287', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (13, 'Langston', 'Averies', '821-919-1967', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (14, 'Tanitansy', 'Quinn', '914-839-4992', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (15, 'Pietra', 'Timcke', '158-987-3810', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (16, 'Ema', 'Kinnoch', '194-694-5585', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (17, 'Shaylynn', 'Morson', '246-755-4097', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (18, 'Son', 'O''Loghlen', '558-776-0105', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (19, 'Veronika', 'MacSharry', '385-362-2668', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (20, 'Dorotea', 'Glancy', '948-424-4965', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (21, 'Shina', 'Acland', '388-233-9111', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (22, 'Perry', 'Noteyoung', '730-592-0412', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (23, 'Angelica', 'Quail', '305-241-9564', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (24, 'Svend', 'Hardi', '229-859-5950', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (25, 'Tristam', 'MacGettigen', '508-106-3233', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (26, 'Angie', 'Brandenburg', '182-659-3087', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (27, 'Pammi', 'Hymus', '215-345-6422', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (28, 'Luke', 'Billion', '340-916-7859', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (29, 'Cosimo', 'Van Daalen', '756-659-4419', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (30, 'Meier', 'Ilbert', '979-741-7579', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (31, 'Germayne', 'Guinan', '822-980-6886', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (32, 'Alana', 'Sinclair', '915-846-9808', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (33, 'Jillana', 'Nottingam', '719-918-7916', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (34, 'Shelby', 'Fisby', '893-708-0284', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (35, 'Modesty', 'Pask', '203-930-3606', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (36, 'Saleem', 'Rankin', '254-569-5777', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (37, 'Cherri', 'Ollivierre', '113-467-3070', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (38, 'Quinn', 'Stiffell', '828-618-0200', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (39, 'Alexei', 'Camellini', '792-785-8745', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (40, 'Leora', 'Fallon', '389-818-2206', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (41, 'Reed', 'Marchi', '851-456-4857', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (42, 'Bevan', 'Farrears', '462-260-8586', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (43, 'Craig', 'Elcomb', '751-740-3471', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (44, 'Raymond', 'Downs', '311-735-4564', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (45, 'Lizabeth', 'Wintle', '867-866-9685', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (46, 'Hagan', 'Ashe', '528-380-2198', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (47, 'Amara', 'Bostock', '804-629-6279', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (48, 'Agneta', 'Peracco', '966-647-6156', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (49, 'Jecho', 'Bilborough', '729-498-3266', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (50, 'Adaline', 'Isakson', '614-414-2961', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (51, 'Neddy', 'Palfreyman', '791-214-9092', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (52, 'Drew', 'Pitman', '717-127-2491', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (53, 'Ernesta', 'Apps', '948-576-1525', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (54, 'Shurlocke', 'Dirand', '349-874-7776', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (55, 'Chandler', 'Soda', '116-430-9036', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (56, 'Ariella', 'Woolens', '390-708-4962', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (57, 'Delano', 'Thys', '744-398-2802', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (58, 'Zeb', 'Drillingcourt', '771-936-8419', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (59, 'Pollyanna', 'Kornilyev', '615-908-3316', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (60, 'Moira', 'Kinane', '801-810-5594', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (61, 'Dede', 'Jaggers', '837-784-7555', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (62, 'Arlen', 'Lefridge', '632-158-3106', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (63, 'Floyd', 'Cejka', '649-618-4350', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (64, 'Nicolais', 'Cawdery', '256-243-7331', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (65, 'Garnette', 'Toth', '585-128-7923', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (66, 'Meaghan', 'Tapsell', '259-328-0367', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (67, 'Crosby', 'O''Dea', '888-394-3310', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (68, 'Corilla', 'Jinks', '966-805-5004', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (69, 'Cleopatra', 'Sampey', '819-802-1706', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (70, 'Brandise', 'Milstead', '949-476-0921', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (71, 'Malcolm', 'MacDwyer', '148-793-8763', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (72, 'Dex', 'Carlon', '710-482-5072', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (73, 'Dilly', 'Heddan', '752-711-0942', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (74, 'Haley', 'Burnand', '235-157-6572', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (75, 'Stavro', 'Noke', '151-378-0676', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (76, 'Hoyt', 'Hiddsley', '702-671-7609', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (77, 'Hakeem', 'Ailsbury', '821-834-2701', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (78, 'Lexy', 'Monteath', '336-172-7621', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (79, 'Onfre', 'Brodley', '672-567-2706', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (80, 'Saloma', 'Prestney', '617-368-6886', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (81, 'Haskell', 'Smout', '446-154-3816', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (82, 'Clarance', 'Dudeney', '148-892-0136', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (83, 'Chen', 'Vassman', '810-632-0217', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (84, 'Remy', 'Snufflebottom', '921-115-9684', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (85, 'Colver', 'Pherps', '519-877-7486', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (86, 'Myrilla', 'Addinall', '847-156-7283', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (87, 'Lanae', 'Belk', '510-787-1346', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (88, 'Dorella', 'Josefer', '381-428-6408', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (89, 'Madeleine', 'Perren', '219-257-3560', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (90, 'Leone', 'Basill', '769-146-7482', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (91, 'Thorstein', 'Shewan', '560-294-3751', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (92, 'Meredith', 'Sothern', '177-792-3707', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (93, 'Daryl', 'Tourmell', '636-326-6245', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (94, 'Nola', 'Tripe', '863-822-0438', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (95, 'Luciana', 'Thomsen', '733-957-4459', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (96, 'Norbert', 'Rosenvasser', '735-477-0370', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (97, 'Forest', 'Jirick', '317-313-2742', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (98, 'Querida', 'Downage', '821-459-9844', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (99, 'Matthew', 'Mcwhinney', '219-196-0905', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (100, 'Tawnya', 'Gillion', '983-626-1375', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (101, 'Keeley', 'Ibberson', '810-187-9256', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (102, 'Cathe', 'Darrow', '521-813-4082', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (103, 'Lexie', 'Corbie', '154-809-5316', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (104, 'Nate', 'Kynd', '589-208-3226', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (105, 'Waring', 'Farra', '795-716-9490', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (106, 'Leona', 'Kilcullen', '142-427-5930', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (107, 'Pearla', 'Donnell', '694-108-6079', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (108, 'Lina', 'Bools', '644-528-8339', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (109, 'Aldo', 'Goodsell', '696-287-5011', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (110, 'Nehemiah', 'MacDearmid', '585-246-3209', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (111, 'Jeniffer', 'Shugg', '915-216-1683', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (112, 'Ardelis', 'Petrusch', '312-795-8932', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (113, 'Bess', 'Kelby', '834-745-6067', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (114, 'Teodor', 'Lints', '364-970-2018', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (115, 'Clio', 'Casbon', '956-320-5481', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (116, 'Olympe', 'Margetson', '440-180-4446', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (117, 'Edithe', 'McIlwaine', '830-188-7499', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (118, 'Lorita', 'Smedley', '583-541-8713', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (119, 'Felicdad', 'Roddell', '926-691-8014', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (120, 'Brena', 'Bradane', '216-967-6682', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (121, 'Angelica', 'Janecek', '672-235-2808', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (122, 'Eadmund', 'Gymblett', '402-344-3895', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (123, 'Darya', 'Fidian', '196-125-2046', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (124, 'Duane', 'Rosenzveig', '602-824-6139', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (125, 'Eva', 'Obern', '613-854-6437', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (126, 'Allie', 'Spalls', '798-984-9657', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (127, 'Ag', 'Banes', '693-499-5796', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (128, 'Berkley', 'Bogue', '586-283-4381', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (129, 'Flin', 'Impey', '309-851-9941', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (130, 'Adrianna', 'Scryne', '344-170-8475', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (131, 'Annabela', 'McCaskell', '511-836-6580', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (132, 'Abbye', 'Throssell', '379-249-8016', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (133, 'Flory', 'Rodden', '911-258-3736', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (134, 'Lorettalorna', 'Betty', '374-380-0159', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (135, 'Mick', 'Boyington', '813-965-6324', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (136, 'Lance', 'Jelk', '713-630-8477', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (137, 'Cesare', 'Manlow', '261-835-8467', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (138, 'Marcel', 'Soan', '649-129-0061', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (139, 'Oliviero', 'Megson', '998-887-4345', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (140, 'Vito', 'Castanone', '906-510-6902', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (141, 'Elisabet', 'Mealand', '967-688-6408', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (142, 'Shara', 'Philcott', '462-556-6434', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (143, 'Garrott', 'Ronaghan', '355-357-4304', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (144, 'Orelle', 'Bellin', '912-458-4039', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (145, 'Siward', 'Orbell', '899-817-3778', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (146, 'Tarra', 'Whyley', '661-391-2068', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (147, 'Zondra', 'Deaconson', '790-101-9493', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (148, 'Aurthur', 'Lemmon', '397-359-4126', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (149, 'Griffie', 'Tivolier', '479-290-0859', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (150, 'Cash', 'Blewitt', '364-492-1725', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (151, 'Tabina', 'Gebbie', '696-742-1857', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (152, 'Hamid', 'Etteridge', '862-620-1254', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (153, 'Celestine', 'Syred', '330-196-6118', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (154, 'Phillie', 'Karppi', '383-192-9950', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (155, 'Dahlia', 'Ebrall', '981-123-0211', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (156, 'Gisella', 'Brain', '474-607-2265', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (157, 'Eryn', 'Bazelle', '785-458-5063', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (158, 'Hallie', 'Alvarez', '393-932-3022', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (159, 'Brittani', 'Matfin', '878-737-5290', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (160, 'Rouvin', 'Jensen', '554-574-5525', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (161, 'Scottie', 'Rosenzwig', '338-452-1649', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (162, 'Jennine', 'Upex', '225-967-8128', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (163, 'Coralyn', 'McRamsey', '347-752-8400', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (164, 'Danell', 'Redgrove', '620-569-9205', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (165, 'Eirena', 'Steinor', '464-865-0987', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (166, 'Archibold', 'Witard', '701-938-7146', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (167, 'George', 'Grigoire', '598-915-7502', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (168, 'Sibley', 'Loynes', '387-752-6027', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (169, 'Emanuele', 'Guare', '830-544-5212', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (170, 'Chan', 'Guirard', '729-937-7202', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (171, 'Leesa', 'Scamerdine', '861-446-7737', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (172, 'Merci', 'Terzi', '574-459-8796', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (173, 'Cord', 'Carrabot', '988-788-3883', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (174, 'Garey', 'Weal', '247-261-0402', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (175, 'Hillyer', 'Renneke', '898-939-7747', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (176, 'Pammi', 'Mallan', '301-687-8161', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (177, 'Winne', 'Orrow', '242-503-3561', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (178, 'Clemence', 'Abriani', '462-988-4584', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (179, 'Myron', 'Brannan', '398-276-0994', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (180, 'Paton', 'Claffey', '626-717-6066', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (181, 'Leonerd', 'Dalinder', '826-172-9952', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (182, 'Elinor', 'Coate', '573-252-3730', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (183, 'Benn', 'Snalum', '846-251-9657', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (184, 'Kalli', 'Hulance', '888-947-1001', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (185, 'Justus', 'Shatliffe', '761-108-1709', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (186, 'Maryjane', 'Helliker', '655-562-1839', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (187, 'Niven', 'Clemerson', '187-401-0498', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (188, 'Peri', 'Pidduck', '805-291-1378', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (189, 'Berna', 'Keysall', '520-927-0750', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (190, 'Barbe', 'Gather', '590-782-2932', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (191, 'Mathias', 'Hayesman', '152-716-9267', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (192, 'Anya', 'Hinkins', '823-798-5898', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (193, 'Astra', 'Bubeer', '705-529-9652', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (194, 'Lynsey', 'Butland', '707-916-5428', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (195, 'Salli', 'Doxey', '347-965-6529', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (196, 'Hakeem', 'Caldes', '940-888-7560', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (197, 'Ericka', 'Martlew', '562-830-5698', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (198, 'Eugine', 'Boxill', '670-744-1507', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (199, 'Darrin', 'Godbold', '705-663-0856', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (200, 'Lucia', 'Mattek', '127-437-9194', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (201, 'Rurik', 'Clineck', '311-711-5524', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (202, 'Janela', 'McQuarrie', '837-842-8471', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (203, 'Griswold', 'Saundercock', '674-424-4466', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (204, 'Oriana', 'Craske', '166-719-8217', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (205, 'Ofella', 'Newe', '779-552-5044', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (206, 'Tallie', 'Hatje', '823-755-5767', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (207, 'Lynne', 'Thornewell', '574-936-7331', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (208, 'Carey', 'Spicer', '139-233-6163', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (209, 'Lianna', 'Theseira', '631-431-5057', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (210, 'Mira', 'Smitheman', '940-895-2783', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (211, 'Eden', 'Livoir', '827-317-2858', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (212, 'Inge', 'Jedrachowicz', '704-561-4864', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (213, 'Peder', 'Alexsandrev', '153-640-4481', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (214, 'Carlita', 'Ramsby', '318-859-2665', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (215, 'Dorette', 'Fenty', '584-452-5109', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (216, 'Esta', 'Newlove', '509-573-9421', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (217, 'Marybelle', 'Rapley', '337-997-4949', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (218, 'Anitra', 'Bilsford', '532-984-1453', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (219, 'Lizbeth', 'Sandells', '899-318-4744', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (220, 'Sibyl', 'McFadden', '575-563-2894', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (221, 'Jacynth', 'Munton', '774-598-0243', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (222, 'Sayre', 'Sneesby', '910-225-1584', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (223, 'Adey', 'Caillou', '146-344-5650', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (224, 'Archibold', 'Edelheit', '489-455-3073', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (225, 'William', 'Blacktin', '817-560-5228', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (226, 'Dario', 'Bradford', '587-524-1687', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (227, 'Magdalene', 'Altham', '545-229-0149', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (228, 'Johnath', 'Paskins', '914-155-3354', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (229, 'Linc', 'Labbati', '519-629-9083', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (230, 'Gustaf', 'Imrie', '287-641-5895', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (231, 'Mortie', 'Dreger', '284-268-8097', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (232, 'Lindsey', 'Coult', '488-892-8000', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (233, 'Regen', 'Charlton', '873-312-6729', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (234, 'Mario', 'Griffitts', '435-881-7735', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (235, 'Palmer', 'Poe', '773-228-2041', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (236, 'Oran', 'Capineer', '542-647-8820', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (237, 'Loise', 'Bohin', '478-898-0605', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (238, 'Yance', 'Matthieson', '255-805-7712', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (239, 'Maurise', 'Tire', '236-555-5127', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (240, 'Rodina', 'Clawley', '169-574-2528', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (241, 'Reinhard', 'Duns', '231-194-1442', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (242, 'Alissa', 'Lanfere', '712-607-7688', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (243, 'Fonz', 'Ginglell', '792-892-8813', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (244, 'Stephie', 'Emer', '979-548-6010', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (245, 'Chancey', 'Fillgate', '373-877-1074', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (246, 'Ulysses', 'Pentelo', '112-372-1985', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (247, 'Ginger', 'Locket', '534-479-9770', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (248, 'West', 'Stair', '578-328-7740', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (249, 'Fidelity', 'Eakins', '231-330-9700', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (250, 'Jethro', 'Maleby', '478-967-3723', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (251, 'Camilla', 'MacFadin', '935-284-8656', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (252, 'Delmor', 'Yokel', '920-788-6653', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (253, 'Sloane', 'Robson', '931-203-2020', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (254, 'Gigi', 'Teodorski', '141-198-7726', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (255, 'Flint', 'Filde', '443-943-2485', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (256, 'Monro', 'Halstead', '506-652-9444', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (257, 'Elana', 'Geere', '516-300-0819', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (258, 'Euell', 'Irnis', '865-479-0903', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (259, 'Teddie', 'Ludron', '569-168-5189', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (260, 'Alane', 'Pinch', '895-310-1372', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (261, 'Duke', 'Synder', '167-151-8998', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (262, 'Tallie', 'Robbert', '845-502-7900', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (263, 'Constantine', 'Godard', '834-223-7595', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (264, 'Marney', 'Marshalleck', '377-722-9590', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (265, 'Dena', 'MacVay', '638-495-8767', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (266, 'Sinclare', 'Giscken', '355-355-2612', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (267, 'Alonzo', 'Curzon', '811-893-0647', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (268, 'Bonni', 'MacIllrick', '113-434-3186', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (269, 'Fania', 'Mc Caughen', '729-417-8924', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (270, 'Emilee', 'Durnford', '190-411-4269', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (271, 'Joella', 'Liggens', '796-981-8171', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (272, 'Lorna', 'Childrens', '900-154-6626', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (273, 'Lyndsay', 'Cowdrey', '591-426-7178', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (274, 'Mildrid', 'Schreiner', '902-316-7073', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (275, 'Ashia', 'Dye', '199-436-3422', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (276, 'Auberon', 'Greatrakes', '423-598-8728', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (277, 'Boy', 'Dilleston', '319-219-0949', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (278, 'Neale', 'Wardley', '699-656-9054', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (279, 'Fernando', 'Cotesford', '288-323-6608', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (280, 'Drucy', 'Snawdon', '112-294-4597', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (281, 'Carmelle', 'Boeter', '117-718-5986', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (282, 'Mortie', 'Dalgarnocht', '764-116-4013', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (283, 'Shanna', 'Jaynes', '984-683-1911', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (284, 'Mufinella', 'Mew', '950-483-2785', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (285, 'Julieta', 'Engelbrecht', '665-430-6383', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (286, 'Lockwood', 'Starkie', '918-424-1494', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (287, 'Fraze', 'Eloy', '722-493-4885', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (288, 'Zach', 'Ronca', '448-328-2858', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (289, 'Andrea', 'Tyers', '238-392-1065', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (290, 'Branden', 'Cunradi', '145-602-5419', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (291, 'Fonz', 'Ray', '470-490-9176', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (292, 'Carson', 'Kavanagh', '330-606-4150', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (293, 'Quintin', 'Plumbe', '627-114-0683', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (294, 'Dorise', 'Bowcock', '903-558-6055', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (295, 'Douglass', 'Wright', '451-546-5293', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (296, 'Olly', 'Arthurs', '925-423-7186', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (297, 'Esteban', 'Inworth', '794-616-2438', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (298, 'Gillian', 'Goundsy', '824-597-3918', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (299, 'Barnie', 'Waterman', '394-834-6642', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (300, 'Joseph', 'Gotfrey', '257-660-5459', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (301, 'Clara', 'Sives', '729-355-7091', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (302, 'Rozanne', 'MacKenny', '523-854-8641', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (303, 'Wendie', 'Mulvany', '828-782-8217', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (304, 'Olenka', 'Trendle', '989-768-5872', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (305, 'Kelley', 'Rozea', '787-810-2696', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (306, 'Abeu', 'Choat', '525-493-9354', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (307, 'Andreana', 'Scoyne', '721-537-1823', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (308, 'Florian', 'Naire', '396-807-5754', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (309, 'Shannen', 'Denzey', '987-163-6255', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (310, 'Craggy', 'Litster', '848-422-6154', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (311, 'Carita', 'Westoll', '561-149-6573', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (312, 'Shermy', 'Smallsman', '339-335-9622', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (313, 'Randal', 'Hartrick', '430-961-8207', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (314, 'Cindie', 'Pilger', '593-141-0870', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (315, 'Cobb', 'Youdell', '679-224-1988', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (316, 'Griffin', 'Trengrove', '611-354-5687', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (317, 'Clare', 'Gianinotti', '420-218-2260', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (318, 'Orren', 'Beccles', '754-897-1923', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (319, 'Ysabel', 'Volonte', '289-632-9093', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (320, 'Fawnia', 'Harverson', '156-853-4117', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (321, 'Sarena', 'Melia', '788-244-7730', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (322, 'Jeffrey', 'Seed', '282-739-9800', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (323, 'Ogdan', 'Asmus', '181-584-9290', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (324, 'Ham', 'Veld', '141-724-7276', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (325, 'Janela', 'Teare', '236-841-8392', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (326, 'Marielle', 'Bathersby', '465-442-9959', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (327, 'Roderigo', 'Milillo', '338-866-3954', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (328, 'Karoly', 'Duhig', '609-753-0295', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (329, 'Gilbertina', 'Deluce', '653-455-5626', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (330, 'Mallory', 'Simondson', '493-951-6192', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (331, 'Archibaldo', 'Ladewig', '789-816-6360', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (332, 'Cyril', 'Galer', '839-773-5827', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (333, 'Ambrose', 'Topliss', '978-419-4823', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (334, 'Cairistiona', 'Halksworth', '678-329-6669', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (335, 'Neron', 'Digby', '177-943-4992', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (336, 'Ignacio', 'Delafont', '576-921-2094', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (337, 'Arabella', 'Kleuer', '445-757-0779', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (338, 'Becky', 'Giggs', '415-750-3039', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (339, 'Margi', 'Gercke', '700-555-8635', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (340, 'Josi', 'Enevold', '926-861-5346', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (341, 'Roi', 'Origin', '896-623-2886', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (342, 'Carita', 'Gouny', '628-809-7940', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (343, 'Chandra', 'Rushforth', '909-447-6498', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (344, 'Smitty', 'Choat', '554-968-2192', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (345, 'Feodora', 'Hoyes', '876-828-1614', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (346, 'Tudor', 'Berks', '451-253-4663', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (347, 'Torey', 'Lytlle', '488-833-0373', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (348, 'Lynda', 'Kyttor', '196-970-6196', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (349, 'Cos', 'Huttley', '615-914-8737', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (350, 'Kirby', 'Nudde', '890-470-7122', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (351, 'Thane', 'McIlreavy', '839-137-7871', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (352, 'Darsie', 'Rubenov', '510-449-0725', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (353, 'Berti', 'Rozea', '624-833-5160', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (354, 'Randene', 'Hackelton', '360-614-6672', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (355, 'Honor', 'Ruos', '178-825-7917', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (356, 'Alena', 'Tucknott', '103-901-6267', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (357, 'Halli', 'Dunstone', '184-412-7063', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (358, 'Nelson', 'Josskovitz', '776-609-5077', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (359, 'Cris', 'Nendick', '218-780-4179', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (360, 'Petr', 'Kisby', '321-522-9672', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (361, 'Ros', 'Pratty', '382-462-0307', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (362, 'Gonzalo', 'Bezants', '277-691-8670', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (363, 'Natty', 'Hatton', '941-942-8946', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (364, 'Cash', 'Tippler', '426-584-9888', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (365, 'Linn', 'Ramos', '282-377-2279', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (366, 'Martguerita', 'O''Ruane', '859-280-7561', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (367, 'Chip', 'Hullbrook', '285-158-1101', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (368, 'Lurleen', 'Fife', '563-413-7510', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (369, 'Gardener', 'D''Ambrosi', '516-197-1556', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (370, 'Tallulah', 'Drillot', '954-635-9255', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (371, 'Ladonna', 'Hambrook', '664-395-6940', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (372, 'Kathrine', 'De Andisie', '410-728-3526', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (373, 'Sheffield', 'Christophersen', '597-442-2292', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (374, 'Marketa', 'Korneev', '204-587-2116', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (375, 'Dewey', 'Swarbrigg', '222-669-8846', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (376, 'Greg', 'Strachan', '706-738-8062', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (377, 'Normand', 'Pollitt', '543-753-5667', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (378, 'Glyn', 'Hallut', '897-494-3156', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (379, 'Sonnnie', 'Gong', '468-224-6289', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (380, 'Galen', 'Skarman', '949-515-9901', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (381, 'Pavel', 'Picardo', '934-817-2148', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (382, 'Alexis', 'Kondratyuk', '667-604-3345', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (383, 'Seumas', 'Weldon', '556-617-5763', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (384, 'Dewitt', 'Dimanche', '917-655-9804', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (385, 'Nathanael', 'Poxson', '899-243-1187', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (386, 'Niko', 'Giraths', '295-678-4156', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (387, 'Stacy', 'Jacmard', '963-768-8212', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (388, 'Francois', 'Urridge', '103-436-9746', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (389, 'Jojo', 'McFeat', '689-869-4148', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (390, 'Eachelle', 'Lacer', '530-597-6161', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (391, 'Sada', 'Beartup', '866-842-1340', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (392, 'Desmond', 'Shawyers', '560-401-2576', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (393, 'Gena', 'Kemme', '749-595-8968', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (394, 'Dani', 'Lowery', '866-817-1677', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (395, 'Bertha', 'Scarlin', '966-942-2772', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (396, 'Binni', 'Swinn', '691-551-7510', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (397, 'Siegfried', 'Muffett', '937-879-1478', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (398, 'Otha', 'MacPake', '278-210-4114', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (399, 'Joana', 'O''Farris', '991-445-0783', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (400, 'Merill', 'Filipyev', '268-428-9688', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (401, 'Ailina', 'Silverthorne', '836-784-5133', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (402, 'Chloe', 'Mithon', '513-263-8919', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (403, 'Ricky', 'Castanares', '894-583-5655', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (404, 'Madelaine', 'MacFayden', '764-425-2962', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (405, 'Enrico', 'Bozier', '953-147-5609', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (406, 'Merwyn', 'Bonifazio', '299-502-2380', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (407, 'See', 'Stammirs', '196-783-0936', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (408, 'Pippy', 'Ramshay', '467-326-6639', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (409, 'Ginny', 'Pecey', '309-481-4714', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (410, 'Marten', 'Semmens', '508-568-5271', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (411, 'Erl', 'Reynard', '938-792-5948', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (412, 'Tessa', 'Headingham', '735-455-7845', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (413, 'Mikael', 'Dedon', '807-510-7054', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (414, 'Gena', 'MacFarlane', '850-670-9653', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (415, 'Joline', 'd''Escoffier', '284-498-0796', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (416, 'Lukas', 'Feavearyear', '143-202-2125', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (417, 'Nahum', 'Mamwell', '119-760-8024', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (418, 'Harmony', 'Tebboth', '122-298-6009', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (419, 'Katharyn', 'Paolucci', '690-577-1917', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (420, 'Drucy', 'Wiltsher', '417-989-3411', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (421, 'Manda', 'Riseam', '273-252-1329', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (422, 'Terri', 'Battleson', '719-837-5445', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (423, 'Bari', 'Dreye', '142-777-6596', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (424, 'Irvin', 'Phethean', '566-623-3149', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (425, 'Danit', 'Hewins', '630-394-0482', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (426, 'Shani', 'Le Port', '389-397-9898', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (427, 'Madelaine', 'De Roos', '129-434-8179', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (428, 'Shannan', 'Benesevich', '153-708-9587', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (429, 'Giacopo', 'Rupert', '146-823-8777', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (430, 'Brit', 'Picott', '786-965-7835', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (431, 'Lanni', 'Mullord', '535-247-6835', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (432, 'Arlinda', 'Welling', '268-563-9799', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (433, 'Zaneta', 'O''Shee', '221-264-1343', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (434, 'Jordon', 'Spolton', '440-241-7111', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (435, 'Judi', 'Humm', '842-799-3077', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (436, 'Adolph', 'Marquand', '503-778-0165', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (437, 'Thoma', 'Aymer', '473-128-8365', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (438, 'Irvine', 'Breakey', '317-335-9059', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (439, 'Rhoda', 'Crewdson', '489-175-1262', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (440, 'Amabel', 'Mustin', '661-314-8906', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (441, 'Tudor', 'China', '393-446-9594', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (442, 'Tiff', 'Abramino', '128-592-1975', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (443, 'Dewey', 'Ferenc', '242-164-5702', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (444, 'Kristen', 'Plomer', '187-136-2747', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (445, 'Karlis', 'Izaks', '146-965-4283', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (446, 'Gerda', 'Artois', '978-965-2957', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (447, 'Priscilla', 'Duddy', '487-435-6403', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (448, 'Maddy', 'Cann', '960-267-7997', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (449, 'Moina', 'Sparey', '420-965-3346', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (450, 'Amalie', 'Kingzeth', '418-998-2073', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (451, 'Olag', 'Dumke', '789-766-9772', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (452, 'Sibilla', 'Reuther', '451-500-1051', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (453, 'Roseline', 'Goom', '491-921-3639', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (454, 'Corabelle', 'Klishin', '535-401-8847', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (455, 'Ursula', 'Ledgard', '541-701-5864', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (456, 'Leigh', 'Triebner', '340-230-2310', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (457, 'Ade', 'Baroche', '851-568-1328', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (458, 'Giralda', 'Franzolini', '228-724-4650', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (459, 'Atalanta', 'Cake', '624-162-6067', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (460, 'Harlin', 'Haskey', '228-418-9994', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (461, 'Mireille', 'Haines', '531-618-8350', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (462, 'Francklyn', 'Jepps', '588-603-1985', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (463, 'Eleonora', 'Casolla', '468-203-7344', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (464, 'Samara', 'Garces', '354-546-4926', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (465, 'Zebedee', 'Tennet', '210-705-7648', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (466, 'Boycey', 'Hendriksen', '323-192-6944', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (467, 'Avril', 'Leagas', '630-337-8902', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (468, 'Cissiee', 'Loney', '759-869-4282', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (469, 'Rollin', 'Camel', '472-726-1016', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (470, 'Iggie', 'Node', '477-456-0063', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (471, 'Ramona', 'Greystock', '857-238-0828', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (472, 'Sosanna', 'Padwick', '851-894-7597', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (473, 'Billie', 'Trazzi', '843-933-4215', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (474, 'Grantley', 'Klimkiewich', '104-655-2596', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (475, 'Dare', 'Schubert', '840-678-3795', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (476, 'Errol', 'Hatterslay', '428-690-8882', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (477, 'Maisey', 'Avesque', '964-504-6920', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (478, 'Wilona', 'Doram', '465-954-5544', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (479, 'Nataniel', 'Lympenie', '607-399-9937', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (480, 'Kristopher', 'Kenrat', '713-100-1853', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (481, 'Rouvin', 'Loeber', '689-177-4042', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (482, 'Myra', 'Aizikov', '525-820-5578', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (483, 'Jerrilyn', 'Kitney', '952-928-1188', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (484, 'Rena', 'Cooper', '194-463-0849', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (485, 'Christen', 'Clitheroe', '848-880-7734', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (486, 'Sherlock', 'Curgenven', '782-193-1846', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (487, 'Marinna', 'Collett', '804-551-1200', 'Elevator Specialist');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (488, 'Golda', 'Gimbart', '282-892-3856', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (489, 'Genvieve', 'Giovannini', '356-992-3732', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (490, 'Garrek', 'Dicks', '925-628-1575', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (491, 'Neilla', 'Harborow', '423-249-1880', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (492, 'Cordie', 'Gerold', '614-951-2154', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (493, 'Raven', 'Bruun', '905-100-6608', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (494, 'Jerry', 'Condell', '308-225-8127', 'HVAC Technician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (495, 'Elga', 'Tabb', '216-828-3974', 'General Maintenance');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (496, 'Pierce', 'Shafier', '880-986-1483', 'IT Support');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (497, 'Algernon', 'Ruf', '248-535-7125', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (498, 'Conn', 'Rusbridge', '223-866-0025', 'Plumber');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (499, 'Basile', 'Von Brook', '134-285-4958', 'Electrician');
INSERT INTO STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) VALUES (500, 'Cindee', 'Sacks', '135-402-5673', 'HVAC Technician');
