insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (1, 65, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (2, 58, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (3, 97, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (4, 62, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (5, 49, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (6, 26, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (7, 70, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (8, 32, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (9, 34, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (10, 45, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (11, 1, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (12, 2, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (13, 48, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (14, 4, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (15, 96, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (16, 84, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (17, 91, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (18, 64, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (19, 41, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (20, 66, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (21, 95, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (22, 51, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (23, 4, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (24, 36, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (25, 65, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (26, 77, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (27, 71, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (28, 52, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (29, 82, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (30, 34, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (31, 33, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (32, 9, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (33, 48, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (34, 81, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (35, 39, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (36, 13, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (37, 45, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (38, 3, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (39, 79, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (40, 51, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (41, 86, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (42, 1, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (43, 35, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (44, 67, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (45, 64, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (46, 18, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (47, 36, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (48, 3, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (49, 68, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (50, 52, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (51, 58, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (52, 50, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (53, 79, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (54, 19, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (55, 45, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (56, 35, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (57, 71, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (58, 58, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (59, 15, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (60, 65, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (61, 75, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (62, 38, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (63, 36, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (64, 28, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (65, 61, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (66, 18, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (67, 50, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (68, 61, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (69, 62, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (70, 75, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (71, 77, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (72, 26, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (73, 10, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (74, 44, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (75, 22, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (76, 1, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (77, 31, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (78, 51, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (79, 16, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (80, 32, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (81, 31, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (82, 56, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (83, 97, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (84, 13, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (85, 22, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (86, 7, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (87, 67, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (88, 48, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (89, 27, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (90, 23, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (91, 88, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (92, 44, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (93, 52, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (94, 9, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (95, 14, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (96, 81, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (97, 41, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (98, 85, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (99, 78, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (100, 54, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (101, 38, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (102, 26, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (103, 32, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (104, 65, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (105, 2, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (106, 40, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (107, 35, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (108, 90, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (109, 29, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (110, 60, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (111, 20, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (112, 86, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (113, 31, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (114, 56, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (115, 88, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (116, 69, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (117, 58, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (118, 40, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (119, 36, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (120, 21, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (121, 4, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (122, 8, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (123, 43, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (124, 9, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (125, 8, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (126, 84, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (127, 31, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (128, 16, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (129, 74, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (130, 6, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (131, 91, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (132, 36, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (133, 35, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (134, 94, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (135, 10, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (136, 10, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (137, 3, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (138, 27, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (139, 57, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (140, 100, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (141, 94, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (142, 97, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (143, 49, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (144, 49, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (145, 56, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (146, 62, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (147, 86, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (148, 55, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (149, 91, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (150, 87, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (151, 39, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (152, 76, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (153, 24, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (154, 10, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (155, 27, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (156, 12, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (157, 98, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (158, 97, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (159, 70, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (160, 59, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (161, 14, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (162, 56, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (163, 18, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (164, 87, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (165, 97, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (166, 46, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (167, 9, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (168, 28, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (169, 11, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (170, 67, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (171, 30, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (172, 72, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (173, 78, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (174, 20, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (175, 32, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (176, 19, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (177, 81, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (178, 55, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (179, 100, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (180, 31, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (181, 49, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (182, 9, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (183, 73, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (184, 3, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (185, 31, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (186, 92, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (187, 35, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (188, 30, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (189, 9, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (190, 84, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (191, 6, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (192, 25, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (193, 81, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (194, 45, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (195, 33, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (196, 12, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (197, 47, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (198, 61, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (199, 46, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (200, 88, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (201, 72, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (202, 50, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (203, 72, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (204, 19, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (205, 92, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (206, 43, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (207, 50, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (208, 41, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (209, 65, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (210, 73, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (211, 42, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (212, 9, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (213, 57, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (214, 99, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (215, 12, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (216, 78, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (217, 66, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (218, 69, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (219, 63, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (220, 28, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (221, 14, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (222, 22, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (223, 99, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (224, 57, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (225, 32, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (226, 17, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (227, 47, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (228, 36, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (229, 10, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (230, 18, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (231, 41, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (232, 52, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (233, 84, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (234, 47, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (235, 59, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (236, 2, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (237, 50, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (238, 99, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (239, 97, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (240, 84, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (241, 100, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (242, 22, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (243, 22, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (244, 84, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (245, 34, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (246, 76, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (247, 23, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (248, 87, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (249, 84, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (250, 65, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (251, 12, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (252, 40, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (253, 44, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (254, 82, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (255, 65, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (256, 52, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (257, 87, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (258, 73, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (259, 58, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (260, 65, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (261, 23, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (262, 16, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (263, 38, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (264, 14, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (265, 69, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (266, 79, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (267, 8, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (268, 70, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (269, 63, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (270, 7, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (271, 6, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (272, 65, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (273, 18, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (274, 55, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (275, 84, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (276, 60, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (277, 34, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (278, 30, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (279, 97, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (280, 3, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (281, 50, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (282, 46, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (283, 93, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (284, 77, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (285, 71, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (286, 88, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (287, 70, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (288, 58, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (289, 42, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (290, 78, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (291, 63, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (292, 46, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (293, 30, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (294, 76, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (295, 52, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (296, 98, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (297, 54, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (298, 9, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (299, 39, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (300, 2, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (301, 2, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (302, 84, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (303, 87, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (304, 37, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (305, 13, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (306, 12, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (307, 78, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (308, 78, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (309, 22, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (310, 25, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (311, 98, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (312, 69, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (313, 80, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (314, 78, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (315, 74, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (316, 33, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (317, 92, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (318, 94, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (319, 67, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (320, 27, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (321, 20, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (322, 87, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (323, 72, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (324, 22, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (325, 15, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (326, 63, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (327, 22, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (328, 37, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (329, 100, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (330, 46, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (331, 73, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (332, 61, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (333, 63, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (334, 16, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (335, 8, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (336, 99, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (337, 88, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (338, 34, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (339, 94, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (340, 64, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (341, 23, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (342, 39, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (343, 85, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (344, 35, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (345, 37, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (346, 31, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (347, 73, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (348, 46, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (349, 100, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (350, 96, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (351, 91, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (352, 78, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (353, 96, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (354, 66, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (355, 18, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (356, 23, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (357, 21, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (358, 64, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (359, 76, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (360, 63, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (361, 43, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (362, 79, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (363, 77, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (364, 95, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (365, 33, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (366, 10, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (367, 32, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (368, 53, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (369, 55, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (370, 52, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (371, 22, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (372, 54, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (373, 1, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (374, 14, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (375, 26, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (376, 21, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (377, 10, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (378, 57, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (379, 25, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (380, 14, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (381, 24, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (382, 80, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (383, 58, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (384, 43, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (385, 54, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (386, 50, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (387, 4, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (388, 42, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (389, 66, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (390, 61, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (391, 21, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (392, 79, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (393, 38, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (394, 93, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (395, 42, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (396, 38, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (397, 58, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (398, 43, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (399, 29, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (400, 94, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (401, 35, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (402, 74, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (403, 53, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (404, 85, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (405, 68, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (406, 14, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (407, 31, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (408, 75, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (409, 92, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (410, 94, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (411, 99, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (412, 76, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (413, 75, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (414, 7, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (415, 53, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (416, 78, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (417, 99, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (418, 59, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (419, 94, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (420, 100, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (421, 29, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (422, 98, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (423, 16, 'Parking', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (424, 85, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (425, 68, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (426, 38, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (427, 25, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (428, 13, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (429, 86, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (430, 67, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (431, 28, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (432, 49, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (433, 30, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (434, 22, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (435, 65, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (436, 100, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (437, 60, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (438, 80, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (439, 3, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (440, 9, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (441, 26, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (442, 48, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (443, 20, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (444, 24, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (445, 28, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (446, 18, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (447, 42, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (448, 30, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (449, 43, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (450, 54, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (451, 97, 'Parking', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (452, 52, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (453, 64, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (454, 95, 'Gym', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (455, 7, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (456, 82, 'Kitchen', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (457, 37, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (458, 53, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (459, 34, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (460, 90, 'Pool Area', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (461, 78, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (462, 50, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (463, 84, 'Roof', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (464, 10, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (465, 66, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (466, 30, 'Spa', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (467, 78, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (468, 75, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (469, 1, 'Resturant', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (470, 8, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (471, 54, 'Lobby', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (472, 35, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (473, 16, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (474, 44, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (475, 60, 'Spa', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (476, 55, 'Lobby', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (477, 92, 'Lobby', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (478, 44, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (479, 56, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (480, 63, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (481, 60, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (482, 53, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (483, 22, 'Kitchen', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (484, 50, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (485, 93, 'Parking', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (486, 57, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (487, 83, 'Pool Area', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (488, 95, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (489, 80, 'Spa', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (490, 13, 'Resturant', 'Staff only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (491, 51, 'Roof', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (492, 17, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (493, 42, 'Kitchen', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (494, 97, 'Resturant', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (495, 4, 'Gym', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (496, 33, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (497, 60, 'Roof', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (498, 63, 'Pool Area', 'Public');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (499, 66, 'Gym', 'Maintenance only');
insert into Locations (Location_ID, Floor_Number, Area_Name, Acces_Level) values (500, 91, 'Roof', 'Maintenance only');
