insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (1, 'Currey', 'Castelijn', '119-851-2104', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (2, 'Sadye', 'Covill', '654-884-6963', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (3, 'Way', 'Maidment', '657-407-4242', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (4, 'Avis', 'Dottridge', '893-585-7235', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (5, 'Shelley', 'Timoney', '727-965-8043', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (6, 'Charla', 'Aumerle', '805-552-6178', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (7, 'Sherye', 'Matokhnin', '510-677-6136', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (8, 'Ethe', 'Nowaczyk', '178-842-0294', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (9, 'Nettie', 'Minero', '224-663-0972', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (10, 'Grannie', 'Limeburn', '534-265-5329', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (11, 'Chlo', 'Meale', '805-381-9024', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (12, 'Danica', 'Dunniom', '160-345-4755', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (13, 'Eric', 'Molnar', '128-738-4823', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (14, 'Reilly', 'Dyet', '865-682-5401', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (15, 'Tomaso', 'Kittredge', '514-946-6751', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (16, 'Jean', 'Kiehl', '656-882-5721', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (17, 'Sara', 'Georger', '989-573-6041', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (18, 'Muire', 'Lally', '799-545-2074', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (19, 'Cassy', 'Rainton', '875-838-9844', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (20, 'Tobye', 'Mileham', '836-394-6654', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (21, 'Florentia', 'Gracey', '334-266-9040', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (22, 'Mattias', 'Saller', '265-760-2946', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (23, 'Ryun', 'Dimnage', '231-212-6680', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (24, 'Herve', 'Gegay', '165-977-3935', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (25, 'Mack', 'Livesley', '253-923-7276', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (26, 'Gunther', 'Freshwater', '878-101-8864', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (27, 'Maxi', 'Woolveridge', '886-810-3141', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (28, 'Kira', 'Treagust', '476-485-2441', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (29, 'Vito', 'Gonnin', '891-780-9831', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (30, 'Claudius', 'Cranny', '626-559-5643', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (31, 'Karine', 'Leavry', '460-109-4750', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (32, 'Averyl', 'Deny', '554-871-2630', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (33, 'Herc', 'Rocks', '203-414-8308', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (34, 'Damaris', 'Tuffey', '547-568-3841', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (35, 'Court', 'Dukesbury', '745-631-2387', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (36, 'Marlon', 'Craze', '594-788-6616', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (37, 'Steffie', 'Rother', '524-119-5232', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (38, 'Kerrie', 'Jenoure', '641-773-3809', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (39, 'Chaunce', 'Izhaky', '229-167-9660', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (40, 'Elsy', 'Darleston', '457-854-3507', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (41, 'Gerhardt', 'Ortmann', '195-918-7601', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (42, 'Lucien', 'Frigout', '759-676-6233', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (43, 'Loella', 'Leuren', '209-244-9026', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (44, 'Ely', 'Allison', '155-960-9337', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (45, 'Elwood', 'Brusin', '713-381-2297', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (46, 'Skippy', 'Grzelak', '736-348-0295', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (47, 'Kerri', 'Lusgdin', '285-366-6190', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (48, 'Perri', 'Radley', '506-289-8854', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (49, 'Kiel', 'Boldison', '275-866-1257', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (50, 'Deanna', 'Goatcher', '757-822-4627', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (51, 'Lizzie', 'Lorans', '442-986-4117', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (52, 'Ogdan', 'Soares', '739-648-2134', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (53, 'Saraann', 'Warriner', '533-593-2398', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (54, 'Gallard', 'Penketh', '577-921-1109', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (55, 'Christine', 'Shevlane', '139-466-3096', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (56, 'Gwenny', 'Stanborough', '497-743-3403', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (57, 'Larisa', 'Durston', '552-630-0872', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (58, 'Elfrieda', 'Laxson', '143-243-1534', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (59, 'Kendal', 'Pittendreigh', '293-930-7844', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (60, 'Alasteir', 'Lorne', '106-916-3344', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (61, 'Roxie', 'Dunnion', '341-666-8954', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (62, 'Sigismund', 'Deeney', '328-198-1972', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (63, 'Gardy', 'Simo', '416-130-3382', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (64, 'Filmer', 'Ashburne', '479-707-6929', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (65, 'Yovonnda', 'Lampen', '956-953-1710', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (66, 'Barbette', 'Pendered', '812-811-8602', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (67, 'Paola', 'Ashling', '259-419-5452', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (68, 'Trace', 'Mawne', '745-661-0919', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (69, 'Van', 'Conachie', '795-283-8818', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (70, 'Danyelle', 'Scare', '260-437-8675', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (71, 'Arley', 'Neely', '467-847-6380', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (72, 'Maurie', 'Kensall', '576-828-6448', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (73, 'Reece', 'Escoffrey', '913-746-3699', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (74, 'Madlin', 'Forsythe', '597-286-7978', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (75, 'Vivie', 'Crebo', '923-121-6443', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (76, 'Von', 'Cartmel', '574-976-0672', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (77, 'Willie', 'Lamartine', '853-933-2452', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (78, 'Ethelred', 'Seamon', '329-544-5352', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (79, 'Kaitlynn', 'Beggin', '575-356-3310', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (80, 'Kyrstin', 'Bryett', '381-979-0371', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (81, 'Alistair', 'Lias', '717-802-9598', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (82, 'Benedetta', 'Danzig', '333-853-3912', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (83, 'Steven', 'Plaice', '801-444-3310', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (84, 'Francis', 'Lougheed', '188-611-1658', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (85, 'Filip', 'Leete', '589-687-2615', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (86, 'Arty', 'Prantoni', '791-542-4970', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (87, 'Axel', 'Buzza', '981-958-0492', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (88, 'Wylma', 'Napolitano', '362-427-5847', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (89, 'Goldina', 'Catchpole', '153-736-1497', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (90, 'Tersina', 'Barlow', '917-193-7045', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (91, 'Rolfe', 'Kaufman', '694-319-7095', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (92, 'Grier', 'McGhee', '398-594-7944', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (93, 'Nanete', 'Wolffers', '572-355-4208', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (94, 'Aurthur', 'Trosdall', '616-196-6558', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (95, 'Manolo', 'Challener', '367-693-6408', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (96, 'Inna', 'Verissimo', '833-377-0808', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (97, 'Dorian', 'Montel', '551-809-4589', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (98, 'Dewitt', 'O'' Culligan', '373-123-5975', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (99, 'Mano', 'Verrillo', '198-330-2682', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (100, 'Belinda', 'Wicks', '998-681-4537', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (101, 'Quentin', 'Sexty', '584-589-3464', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (102, 'Kym', 'Trimmell', '235-470-2424', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (103, 'Steward', 'Woodyatt', '936-197-6973', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (104, 'Siouxie', 'Bosquet', '317-794-7537', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (105, 'Georg', 'Upward', '287-479-7900', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (106, 'Ogdon', 'Weed', '939-908-5109', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (107, 'Chadwick', 'Narracott', '978-702-4080', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (108, 'Toby', 'Cometti', '441-366-7496', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (109, 'Saul', 'Swift', '941-866-8905', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (110, 'Dimitri', 'Hefforde', '768-469-5774', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (111, 'Steve', 'Glozman', '501-851-8074', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (112, 'Hedwiga', 'Carabine', '475-156-0116', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (113, 'Dinnie', 'Enstone', '357-807-5018', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (114, 'Tobiah', 'Blackhall', '274-640-5901', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (115, 'Shay', 'Callway', '373-907-1908', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (116, 'Gaynor', 'Simenet', '109-964-5657', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (117, 'Heath', 'Grebert', '748-483-4749', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (118, 'El', 'Cicchinelli', '940-285-0817', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (119, 'Herb', 'Gleder', '114-396-6094', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (120, 'Georgeanne', 'Filippone', '462-625-4679', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (121, 'Archibaldo', 'Shelper', '454-784-1969', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (122, 'Anette', 'Carmel', '130-404-1555', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (123, 'Andrew', 'Blakiston', '138-196-1791', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (124, 'Philomena', 'Fermoy', '288-886-5004', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (125, 'Easter', 'MacNamee', '455-936-0308', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (126, 'Spencer', 'Olek', '345-418-0263', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (127, 'Darrell', 'Heifer', '345-508-3706', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (128, 'Chelsey', 'Wilks', '868-937-2790', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (129, 'Barron', 'Karby', '930-760-2141', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (130, 'Garold', 'Boggis', '664-523-5190', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (131, 'Camile', 'Danielkiewicz', '961-258-7752', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (132, 'Lorrie', 'Rake', '774-768-0073', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (133, 'Alberto', 'Roches', '529-251-6461', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (134, 'Dayna', 'Huband', '411-263-3281', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (135, 'Andrea', 'Winspare', '308-821-0286', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (136, 'Aeriell', 'Alldis', '835-565-3355', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (137, 'Tremain', 'Baudts', '623-550-6932', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (138, 'Druci', 'Walework', '397-328-3907', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (139, 'Twyla', 'Morrill', '124-784-7273', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (140, 'Doug', 'McRorie', '663-990-0837', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (141, 'Kristina', 'O''Sheeryne', '817-540-9154', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (142, 'Bliss', 'Pendre', '638-816-4095', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (143, 'Carr', 'Fretwell', '494-221-0544', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (144, 'Ruby', 'Mitchelhill', '406-545-8868', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (145, 'Dud', 'Raimbauld', '519-204-4700', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (146, 'Mara', 'Mewha', '751-124-7118', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (147, 'Yolanda', 'Yole', '516-552-3091', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (148, 'Hayward', 'Fullard', '987-695-3203', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (149, 'Herrick', 'Killingbeck', '520-996-4184', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (150, 'Orazio', 'Baudain', '797-887-1419', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (151, 'Hillier', 'Duckerin', '542-230-6001', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (152, 'Oliver', 'McGeffen', '962-927-2742', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (153, 'Kiel', 'Sephton', '501-290-5404', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (154, 'Sayre', 'Braisher', '894-560-0117', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (155, 'Jules', 'Barcroft', '118-239-0089', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (156, 'Myriam', 'MacIver', '639-760-5479', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (157, 'Queenie', 'Dono', '436-590-0364', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (158, 'Frederico', 'Klicher', '162-988-1577', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (159, 'Rudy', 'Loftin', '464-421-8548', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (160, 'Francisca', 'Randalson', '984-747-7102', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (161, 'Alberta', 'Planke', '837-827-9056', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (162, 'Misti', 'Stammer', '959-409-9310', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (163, 'Luciano', 'Baggott', '727-453-7796', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (164, 'Toni', 'Lovelock', '518-866-5942', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (165, 'Abba', 'Ryding', '275-956-9677', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (166, 'Mandie', 'Goatcher', '791-531-5490', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (167, 'Lu', 'Paulo', '368-481-5779', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (168, 'Valida', 'Cumberland', '899-480-1031', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (169, 'Zelig', 'Gaffon', '808-540-8165', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (170, 'Ursula', 'Poynser', '342-960-8518', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (171, 'Sallee', 'Caen', '414-729-3338', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (172, 'Jamal', 'Lakey', '855-960-7189', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (173, 'Meredith', 'Kuhl', '920-838-5591', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (174, 'Vito', 'Truse', '948-897-0889', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (175, 'Ugo', 'Anglim', '827-295-0483', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (176, 'Moritz', 'Ortiger', '200-708-8587', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (177, 'Hugues', 'Braunlein', '581-194-0650', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (178, 'Kara', 'Wellings', '805-239-2195', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (179, 'Marika', 'Mendes', '232-119-9957', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (180, 'Delinda', 'Bruhke', '261-770-2460', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (181, 'Marney', 'Burel', '320-678-9156', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (182, 'Marwin', 'Verden', '550-657-1487', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (183, 'Gnni', 'Gilks', '222-703-6078', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (184, 'Ramon', 'Presnail', '475-529-9149', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (185, 'Illa', 'Abatelli', '327-660-5647', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (186, 'Thoma', 'Arangy', '205-344-6026', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (187, 'Bambie', 'Bownes', '771-279-8069', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (188, 'Arden', 'Orpwood', '442-951-9230', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (189, 'Elwin', 'Gawkes', '936-809-7268', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (190, 'Avril', 'Overil', '475-516-8679', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (191, 'Fairlie', 'Penreth', '823-295-4515', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (192, 'Blair', 'Dreinan', '222-605-7207', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (193, 'Thurston', 'Le Noir', '891-748-6228', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (194, 'Cornela', 'Donnan', '976-548-2815', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (195, 'Arabelle', 'Woolham', '354-699-7563', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (196, 'Anabel', 'Lambourne', '951-623-1513', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (197, 'Krista', 'Micah', '500-734-0699', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (198, 'Jerome', 'Vigar', '861-249-3528', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (199, 'Trudy', 'Jerosch', '632-299-0718', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (200, 'Mannie', 'Algeo', '707-539-1319', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (201, 'Michale', 'Haquin', '225-180-6462', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (202, 'Nell', 'Loynton', '516-156-3084', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (203, 'Mirilla', 'McKeighen', '314-442-7280', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (204, 'Joelly', 'Trenoweth', '267-897-1904', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (205, 'Christy', 'Scholtis', '794-960-2926', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (206, 'Merola', 'Ciccotti', '916-816-2120', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (207, 'Pen', 'Bolley', '851-262-5340', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (208, 'Hercule', 'Biddle', '589-194-9849', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (209, 'Chad', 'Craigmyle', '262-906-3199', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (210, 'Belvia', 'Kiefer', '450-305-0060', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (211, 'Emelia', 'Vannini', '230-938-1029', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (212, 'Antons', 'Cuerda', '625-602-3572', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (213, 'Wilow', 'McCroft', '545-584-1826', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (214, 'Roland', 'Spadelli', '418-109-6148', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (215, 'Kariotta', 'Hatz', '288-727-5400', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (216, 'Claus', 'Connealy', '321-474-4737', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (217, 'Paco', 'Waterstone', '510-301-7522', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (218, 'Annnora', 'Orteaux', '798-677-6579', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (219, 'Rollin', 'Artin', '560-380-0448', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (220, 'Bernarr', 'Colegate', '349-692-7267', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (221, 'Guss', 'Southcomb', '941-633-8941', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (222, 'Brandy', 'McGowing', '843-967-8029', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (223, 'Hussein', 'Algate', '925-969-2849', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (224, 'Davey', 'Lere', '228-785-4386', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (225, 'Flora', 'Gyngyll', '345-225-6465', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (226, 'Reg', 'Byford', '136-612-6957', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (227, 'Fraze', 'O''Deegan', '879-269-7294', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (228, 'Carla', 'Diprose', '289-682-2757', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (229, 'Anabella', 'Kilban', '702-475-5428', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (230, 'Dionne', 'Hakonsen', '345-905-7136', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (231, 'Goran', 'Gellier', '729-886-0077', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (232, 'Jedd', 'Plaistowe', '587-341-5295', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (233, 'Gae', 'Mealing', '566-628-3585', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (234, 'Bartolomeo', 'Marvell', '970-759-6656', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (235, 'Gonzalo', 'Fosbraey', '429-400-4712', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (236, 'Karita', 'Papa', '497-603-8387', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (237, 'Lenee', 'Custy', '348-144-1796', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (238, 'Gussi', 'Mooreed', '521-713-1461', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (239, 'Harley', 'Harbison', '820-922-9069', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (240, 'Ellwood', 'Piecha', '686-865-5630', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (241, 'Kristan', 'Whittick', '475-513-4185', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (242, 'Corrianne', 'Sabathe', '138-498-6228', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (243, 'Prince', 'Wickes', '271-859-6690', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (244, 'Philippine', 'Adolphine', '135-938-4019', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (245, 'Mason', 'McEnery', '683-754-6909', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (246, 'Berny', 'Chung', '170-267-1016', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (247, 'Bernardine', 'Kleyn', '372-410-0639', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (248, 'Toby', 'Eplate', '667-144-9628', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (249, 'Gregoor', 'Prickett', '240-373-9006', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (250, 'Saree', 'Neles', '218-377-9534', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (251, 'Aline', 'O'' Kelleher', '416-888-5913', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (252, 'Clair', 'Maiklem', '815-250-5692', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (253, 'Verile', 'Gummer', '680-350-7192', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (254, 'Yard', 'Bangiard', '723-352-7938', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (255, 'Francis', 'Quernel', '739-556-8735', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (256, 'Annabelle', 'Snead', '793-750-8575', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (257, 'Corey', 'Wabersich', '711-368-5293', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (258, 'Natasha', 'Emes', '831-234-2318', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (259, 'Dulcia', 'Vedekhov', '455-431-0386', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (260, 'Coraline', 'Lamacraft', '916-552-8320', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (261, 'Burg', 'Teodoro', '322-987-5096', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (262, 'Carie', 'Eggins', '436-752-1889', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (263, 'Benita', 'Borrell', '973-188-0176', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (264, 'Bondy', 'McQuode', '303-704-9998', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (265, 'Moritz', 'Sammars', '333-427-6148', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (266, 'Eunice', 'Leithgoe', '466-275-2236', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (267, 'Reuben', 'Shorie', '888-805-6233', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (268, 'Lisetta', 'Massenhove', '520-965-1660', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (269, 'Candra', 'Summersett', '732-994-7825', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (270, 'Cyrus', 'Babonau', '898-118-4925', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (271, 'Freeman', 'Wooding', '509-986-6356', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (272, 'Claudio', 'Gladbach', '826-814-6878', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (273, 'Lance', 'Oldham', '798-792-4017', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (274, 'Aldin', 'Cowdroy', '965-544-1935', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (275, 'Upton', 'Sandeland', '314-903-1335', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (276, 'Frederick', 'Djuricic', '528-775-1502', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (277, 'Haily', 'Dwyr', '538-232-0864', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (278, 'Lia', 'Heaney`', '413-114-7619', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (279, 'Myrtle', 'Rude', '981-800-6488', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (280, 'Emyle', 'Minocchi', '722-831-3076', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (281, 'Opal', 'O''Hickee', '111-605-6858', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (282, 'Stephen', 'Lofts', '658-568-4279', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (283, 'Mayer', 'Garlinge', '277-675-8894', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (284, 'Bili', 'Purchase', '701-426-2600', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (285, 'Darlleen', 'Murrison', '685-231-6477', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (286, 'Vic', 'Santo', '122-603-0007', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (287, 'Isabel', 'Fawltey', '264-919-7727', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (288, 'Olympie', 'Lau', '528-499-2529', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (289, 'Zacharie', 'Tarver', '172-225-9266', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (290, 'Bart', 'Sanchez', '301-850-2627', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (291, 'Aigneis', 'Jouandet', '965-975-7208', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (292, 'Nikolas', 'Juliff', '910-831-9435', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (293, 'Linus', 'Louden', '854-237-3344', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (294, 'Eunice', 'Spinella', '906-346-2582', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (295, 'Friedrich', 'Klasing', '478-161-6395', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (296, 'Kiley', 'Haggett', '865-746-9011', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (297, 'Osborne', 'Zavittieri', '489-711-8926', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (298, 'Angel', 'Flemmich', '982-474-0561', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (299, 'Brook', 'Matijasevic', '204-816-1593', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (300, 'Agata', 'Labeuil', '306-512-4281', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (301, 'Woodman', 'O''Grogane', '217-362-4335', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (302, 'Becca', 'Caddan', '375-882-8673', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (303, 'Lynnell', 'Storrar', '870-752-2623', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (304, 'Aleda', 'Vinker', '747-818-3174', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (305, 'Cissy', 'Housbie', '631-384-1664', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (306, 'Winnie', 'Tomkies', '540-353-5699', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (307, 'Brockie', 'MacKerley', '729-466-1615', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (308, 'Salome', 'Lathy', '232-131-4785', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (309, 'Mordy', 'Bonelle', '845-405-0718', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (310, 'Trixi', 'Geill', '304-230-7828', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (311, 'Frasquito', 'Doey', '949-810-1106', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (312, 'Sergent', 'Rootes', '802-682-6672', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (313, 'Abbe', 'Marran', '916-740-0438', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (314, 'Gare', 'Kenshole', '816-797-4673', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (315, 'Tammara', 'Jent', '854-523-2930', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (316, 'Felice', 'Scamaden', '209-148-8526', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (317, 'Dore', 'Paine', '602-111-1394', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (318, 'Gottfried', 'Branch', '598-301-4368', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (319, 'Bordie', 'Frood', '692-385-9113', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (320, 'Kennett', 'Minney', '408-369-7209', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (321, 'Justen', 'Taile', '177-423-6701', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (322, 'Siward', 'Terney', '665-475-1875', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (323, 'Dorian', 'Stitwell', '156-907-3427', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (324, 'Prudy', 'Casa', '248-722-8866', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (325, 'Lazar', 'Meigh', '903-194-2179', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (326, 'Hamish', 'Vinas', '784-778-1350', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (327, 'Pauline', 'Verni', '254-742-7358', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (328, 'Alexio', 'Babinski', '640-962-4972', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (329, 'Bobby', 'Krauze', '277-618-4816', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (330, 'Moina', 'Synke', '349-374-4088', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (331, 'Zorah', 'Guite', '116-632-1868', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (332, 'Joice', 'Rolph', '794-162-2165', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (333, 'Karita', 'Knappe', '133-901-7586', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (334, 'Fitz', 'Dietmar', '361-564-8292', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (335, 'Franny', 'Heck', '618-966-6780', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (336, 'Rickie', 'Quernel', '146-362-7374', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (337, 'Clo', 'Jermy', '376-908-0801', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (338, 'Beckie', 'Lesurf', '515-834-3505', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (339, 'Lyndsie', 'Gumme', '857-357-3798', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (340, 'Jimmy', 'Montes', '815-774-1714', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (341, 'Mordecai', 'Cussins', '632-201-2619', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (342, 'Mahalia', 'Knowlman', '293-236-6279', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (343, 'Christen', 'McHaffy', '438-623-3611', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (344, 'Ann-marie', 'Simounet', '387-119-0183', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (345, 'Kimball', 'Hamber', '683-624-5580', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (346, 'Lou', 'Grandham', '530-712-7448', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (347, 'Burl', 'Lamps', '665-928-5655', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (348, 'Cynde', 'Vischi', '899-586-8620', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (349, 'Theresina', 'Pandya', '569-815-3564', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (350, 'Parker', 'Targett', '992-926-9329', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (351, 'Brandise', 'Skule', '121-391-9443', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (352, 'Tab', 'Tregensoe', '332-667-5358', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (353, 'Giselbert', 'Arbon', '883-520-6972', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (354, 'Quill', 'Inwood', '597-373-7295', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (355, 'Renell', 'Fowley', '249-667-2681', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (356, 'Suzette', 'Honatsch', '459-286-2389', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (357, 'Tera', 'Macvain', '704-920-5446', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (358, 'Cathy', 'Ensor', '435-319-7664', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (359, 'Elvis', 'Sumbler', '226-750-6174', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (360, 'Erinn', 'Mathy', '312-842-2760', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (361, 'Anita', 'Fagan', '698-138-8498', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (362, 'Bevon', 'Sudell', '791-593-9263', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (363, 'Cesya', 'Smalley', '774-697-2044', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (364, 'Nester', 'Bengochea', '577-567-7114', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (365, 'Napoleon', 'Sennett', '662-827-6028', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (366, 'Coreen', 'Rosenkrantz', '744-881-0957', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (367, 'Alwyn', 'Sayre', '797-565-8354', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (368, 'Mano', 'Moxom', '241-482-9179', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (369, 'Glenna', 'Twinning', '102-705-9334', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (370, 'Shannon', 'Duggon', '869-941-8221', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (371, 'Alana', 'Dugall', '367-768-2521', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (372, 'Valeda', 'Drowsfield', '514-293-4668', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (373, 'Hortensia', 'Loftus', '940-251-0474', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (374, 'Kayne', 'Leel', '156-293-1772', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (375, 'Aurel', 'Bowle', '306-460-6374', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (376, 'Stefan', 'Fossick', '908-347-3051', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (377, 'Doralin', 'Sipson', '470-983-3587', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (378, 'Violetta', 'Drysdell', '476-899-0786', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (379, 'Codi', 'Danovich', '790-481-0793', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (380, 'Brandais', 'Di Boldi', '821-409-0722', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (381, 'Teri', 'Marcroft', '456-412-8038', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (382, 'Jess', 'Cantera', '138-471-3122', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (383, 'Dalila', 'Powland', '888-486-3780', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (384, 'Marlin', 'Woolens', '516-240-2489', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (385, 'Janos', 'Thornthwaite', '835-835-9945', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (386, 'Yoshi', 'Verrills', '990-153-4142', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (387, 'Murry', 'Shipston', '278-231-4008', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (388, 'Penn', 'Burr', '492-240-7991', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (389, 'Bertha', 'Anderson', '982-434-9183', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (390, 'Erinn', 'Heisman', '818-351-0735', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (391, 'Pail', 'Stuttard', '366-539-3233', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (392, 'Bernadina', 'Balogun', '264-172-5297', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (393, 'Vivyan', 'Sollom', '336-196-7189', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (394, 'Urson', 'Mingardo', '200-671-2700', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (395, 'Pat', 'Milkins', '391-941-5175', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (396, 'Grantley', 'McGiveen', '956-997-8694', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (397, 'Tiphany', 'Gilhouley', '816-626-3708', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (398, 'Lammond', 'Acreman', '176-516-3479', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (399, 'Far', 'Jell', '601-851-6622', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (400, 'Cleveland', 'Huchot', '517-675-4748', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (401, 'Tod', 'Aikin', '964-662-3649', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (402, 'Dolli', 'Dolle', '760-854-3072', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (403, 'Mordecai', 'Orys', '956-717-1832', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (404, 'Vonni', 'Dole', '624-995-7827', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (405, 'Dasha', 'Deboo', '424-868-4432', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (406, 'Ranique', 'Pinkerton', '974-991-1520', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (407, 'Dinnie', 'Surmon', '562-870-0288', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (408, 'Vasili', 'Bortol', '611-945-4903', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (409, 'Verile', 'Whitley', '621-521-6822', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (410, 'Lillis', 'Gillan', '460-145-6695', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (411, 'Ber', 'Lishman', '958-580-6481', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (412, 'Kristen', 'Soro', '838-789-4461', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (413, 'Leodora', 'Hartshorn', '973-128-0961', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (414, 'Ernestus', 'Radclyffe', '810-667-4871', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (415, 'Hillary', 'Yendall', '672-465-9003', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (416, 'Bride', 'O''Loughnan', '387-380-1524', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (417, 'Erma', 'Veysey', '374-865-0264', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (418, 'Fanni', 'Guyers', '885-264-8510', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (419, 'Celeste', 'Jelk', '105-362-6236', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (420, 'Allan', 'Enderlein', '989-990-5559', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (421, 'Howey', 'Drysdale', '269-652-5617', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (422, 'Virgie', 'Danielou', '247-100-2755', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (423, 'Brunhilde', 'Whitney', '738-807-9516', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (424, 'Rafael', 'MacAlinden', '467-185-4465', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (425, 'Bliss', 'Gamwell', '523-557-7830', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (426, 'Kameko', 'McCudden', '998-433-1948', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (427, 'Kellsie', 'Learmonth', '729-602-0718', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (428, 'Marilee', 'Walliker', '651-771-2546', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (429, 'Julian', 'Skinner', '682-942-3283', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (430, 'Janine', 'Autie', '945-106-0306', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (431, 'Jackson', 'Thrussell', '841-223-8500', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (432, 'Dur', 'Chellenham', '463-818-3089', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (433, 'Emalee', 'McCandless', '984-222-8328', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (434, 'Van', 'Oke', '550-558-4836', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (435, 'Jecho', 'MacLeod', '252-346-6290', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (436, 'Torry', 'Goose', '456-791-5618', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (437, 'Tessie', 'Stopper', '610-422-5319', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (438, 'Ginny', 'Searle', '715-419-0323', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (439, 'Cecil', 'McPhilip', '321-895-8118', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (440, 'Pattie', 'Lattka', '828-398-6465', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (441, 'Carmina', 'Longwood', '423-237-7037', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (442, 'Herc', 'Bernardin', '655-801-6282', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (443, 'Jordan', 'Aleksidze', '354-275-5355', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (444, 'Jaime', 'Sarath', '309-315-7694', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (445, 'Jeff', 'Scatcher', '434-458-5496', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (446, 'Katy', 'Batte', '438-720-6684', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (447, 'Cathyleen', 'Macewan', '955-532-9860', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (448, 'Isador', 'Sink', '528-985-0703', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (449, 'Aarika', 'Duffield', '894-749-3613', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (450, 'Eddie', 'Harback', '967-669-4550', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (451, 'Virgil', 'Suatt', '283-553-0240', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (452, 'Carlie', 'Feacham', '408-984-0390', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (453, 'Tobe', 'Cardall', '596-717-8734', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (454, 'Ynes', 'Fynn', '887-480-5623', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (455, 'Hetty', 'Trethowan', '500-181-0733', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (456, 'Demetre', 'MacAllan', '477-913-5739', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (457, 'Melba', 'Brandsen', '635-872-8221', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (458, 'Karlan', 'Dunnion', '695-271-8915', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (459, 'Allis', 'Glasner', '553-377-3251', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (460, 'Gawen', 'Steely', '576-309-6514', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (461, 'Mala', 'Dyerson', '736-744-7135', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (462, 'Emmye', 'De Michele', '915-800-8965', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (463, 'Ulrike', 'Orred', '704-842-7726', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (464, 'Garold', 'Hutchison', '306-162-1184', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (465, 'Pauletta', 'Paylie', '469-500-4178', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (466, 'Gael', 'Culbard', '484-312-2744', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (467, 'Anetta', 'Trythall', '185-240-2239', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (468, 'Penelopa', 'Wolseley', '436-331-9349', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (469, 'Rodolphe', 'Peeke', '963-953-6499', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (470, 'Tuck', 'McCourtie', '911-134-2748', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (471, 'Lem', 'Widdowson', '426-280-1317', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (472, 'Emerson', 'Franzonetti', '878-816-8445', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (473, 'Jourdain', 'Seward', '538-683-5817', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (474, 'Loralie', 'Magwood', '655-319-4122', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (475, 'Patty', 'Blazej', '433-149-1657', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (476, 'Marcus', 'Molineaux', '444-831-8323', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (477, 'Durand', 'McKenna', '322-760-6430', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (478, 'Queenie', 'Rown', '442-144-6127', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (479, 'Eolanda', 'Fieldgate', '355-593-5201', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (480, 'Dierdre', 'Keveren', '584-426-8059', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (481, 'Marline', 'Sheekey', '139-312-0279', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (482, 'Pris', 'Radbourn', '369-796-9645', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (483, 'Porty', 'Castana', '373-594-4765', 'IT');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (484, 'Ruthi', 'Chester', '234-285-2965', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (485, 'Valencia', 'Brittan', '924-291-6337', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (486, 'Cele', 'Benedyktowicz', '651-417-5235', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (487, 'Astrid', 'Petrina', '242-605-0976', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (488, 'Benedikt', 'Essam', '699-843-3958', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (489, 'Taber', 'Davenell', '259-488-7305', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (490, 'Johny', 'Authers', '311-174-5532', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (491, 'Kaine', 'Wofenden', '647-828-9741', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (492, 'Katy', 'Fencott', '201-135-2449', 'Plumber');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (493, 'Wynn', 'Tremblay', '566-668-5143', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (494, 'Clarissa', 'MacGilrewy', '620-891-7393', 'Lift Technician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (495, 'Martguerita', 'Tadgell', '826-866-6076', 'General');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (496, 'Roxanna', 'Lough', '426-655-5354', 'Electrician');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (497, 'Erhart', 'Innocenti', '331-206-1643', 'HVAC');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (498, 'Celestina', 'Titcomb', '662-725-2575', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (499, 'Forrest', 'Healing', '367-762-1344', 'Maintenance');
insert into STAFF (Staff_ID, First_Name, Last_Name, Phone_Number, Expertise) values (500, 'Ruprecht', 'Foard', '796-553-8005', 'Lift Technician');
